
name: Build Docker Image
on: push
jobs:
  build-docker-image:
    runs-on: t67llm9p7m.registry.depot.dev/my-ci-image:latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Build and Push with Depot
        uses: depot/build-push-action@v1
        with:
          context: .
          token: ${{ secrets.DEPOT_TOKEN }}
          project: 2mtnv574xd
          secrets: |
            "DEPOT_TOKEN=${{ secrets.DEPOT_TOKEN }}"
          save: true
          save-tags: |
            latest
            ${{ github.sha }}
