package dns

import (
	"reflect"
	"testing"
)

func TestPlainNameservers(t *testing.T) {
	for _, tt := range []struct {
		name, config string
		want         []string
	}{
		{"vm3", "nameserver 8.8.8.8\nnameserver 9.9.9.9\n", []string{"8.8.8.8", "9.9.9.9"}},
		{"preserve upstreams", "nameserver 10.0.0.2\nnameserver 2606:4700:4700::1111\n", []string{"10.0.0.2", "2606:4700:4700::1111"}},
		{"managed", "# Generated by Tailscale\nnameserver 100.100.100.100\n", nil},
		{"search", "nameserver 10.0.0.2\nsearch example.internal\n", nil},
		{"options", "nameserver 8.8.8.8\noptions ndots:5\n", nil},
		{"local", "nameserver 127.0.0.53\n", nil},
		{"ipv6 local", "nameserver ::1\n", nil},
		{"invalid", "nameserver invalid\n", nil},
		{"empty", "", nil},
	} {
		t.Run(tt.name, func(t *testing.T) {
			if got := plainNameservers(tt.config); !reflect.DeepEqual(got, tt.want) {
				t.Fatalf("got %v, want %v", got, tt.want)
			}
		})
	}
}
