  name: Reusable

  on:
    workflow_call: {}

  concurrency:
    group: rails-build-${{ github.sha }}
    cancel-in-progress: false

  jobs:
    inner-job:
      runs-on: depot-ubuntu-24.04
      timeout-minutes: 3
      steps:
        - name: Sleep
          run: sleep 90
